ValueError
Traceback (most recent call last)
<ipython-input-5-733240eeendbf> in <module>()
        2 sum = 0
        3 for data in file;
 ---->  4          Sum = sum + int(dat)
        5 print (sum)
        
ValueError: invalid literal for int() with base 10: 'a\n'
